### ISSUE TITLE
[Bug]: Not working if used primary column not ID

### ISSUE THREAD

**Issue by evoart-studio** [athphane/filament-editorjs#2]
### What happened?

$getFileAttachmentUrl() always null if in model used uuid, not id
![image](https://github.com/user-attachments/assets/6b7ce567-3aa9-4eb6-96c6-c7ed37a18ad9)

### How to reproduce the bug

use not id as primary column in model

### Package Version

1.0.6

### PHP Version

8.3.0

### Laravel Version

11.10.0

### Which operating systems does with happen with?

macOS

**Comment by athphane** [comment]
Yeah this makes sense. I think the proper way to go on about this would be to use `$model->getKey()` instead of directly getting the ID. 

I personally have not used UUIDs as primary keys in my models so I do not know exactly how it behaves. If you can test with the solution I just gave and submit a PR, I would greatly appreciate it.

**Comment by athphane** [comment]
Closed in #3
